-- AlterTable
ALTER TABLE `Poll` ADD COLUMN     `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `endsAt` DATETIME(3),
    ADD COLUMN     `isOpen` BOOLEAN NOT NULL DEFAULT true;
